/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gko3.torrentprovider.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProviderServerCmdType implements org.apache.thrift.TEnum {
  CMD_STATUS(0),
  CMD_STOP(1),
  CMD_UNKNOWN(2);

  private final int value;

  private ProviderServerCmdType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProviderServerCmdType findByValue(int value) { 
    switch (value) {
      case 0:
        return CMD_STATUS;
      case 1:
        return CMD_STOP;
      case 2:
        return CMD_UNKNOWN;
      default:
        return null;
    }
  }
}
